# SPDX-FileCopyrightText: 2023 thecheeseman
#
# SPDX-License-Identifier: CC0-1.0

# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x86
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x86)
  iocodcore_config = debug_x86

else ifeq ($(config),debug_x86_64)
  iocodcore_config = debug_x86_64

else ifeq ($(config),release_x86)
  iocodcore_config = release_x86

else ifeq ($(config),release_x86_64)
  iocodcore_config = release_x86_64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := iocodcore

.PHONY: all clean help $(PROJECTS) Core

all: $(PROJECTS)

Core: iocodcore

iocodcore:
ifneq (,$(iocodcore_config))
	@echo "==== Building iocodcore ($(iocodcore_config)) ===="
	@${MAKE} --no-print-directory -C Source/Core -f Makefile config=$(iocodcore_config)
endif

clean:
	@${MAKE} --no-print-directory -C Source/Core -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x86"
	@echo "  debug_x86_64"
	@echo "  release_x86"
	@echo "  release_x86_64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   iocodcore"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"