# Check STDC Headers
# Based on https://gist.github.com/likema/97841d77e5f384fbdb46629c5b429013

macro(CHECK_STDC_HEADERS)
    if (NOT CMAKE_REQUIRED_QUIET)
        message(STATUS "Checking for ANSI C header files")
    endif()
    
    check_include_files("assert.h;ctype.h;errno.h;float.h;limits.h;locale.h;math.h;setjmp.h;signal.h;stdarg.h;stddef.h;stdio.h;stdlib.h;string.h;time.h" STDC_HEADERS)
    if (STDC_HEADERS)
        message(STATUS "ANSI C headers found")

        set(HAVE_ASSERT_H 1)
        set(HAVE_CTYPE_H 1)
        set(HAVE_ERRNO_H 1)
        set(HAVE_FLOAT_H 1)
        set(HAVE_LIMITS_H 1)
        set(HAVE_LOCALE_H 1)
        set(HAVE_MATH_H 1)
        set(HAVE_SETJMP_H 1)
        set(HAVE_SIGNAL_H 1)
        set(HAVE_STDARG_H 1)
        set(HAVE_STDDEF_H 1)
        set(HAVE_STDIO_H 1)
        set(HAVE_STDLIB_H 1)
        set(HAVE_STRING_H 1)
        set(HAVE_TIME_H 1)
    else()
        message(STATUS "Couldn't find all ANSI C headers, checking individually")

    check_include_files(assert.h HAVE_ASSERT_H)
    check_include_files(ctype.h HAVE_CTYPE_H)
    check_include_files(errno.h HAVE_ERRNO_H)
    check_include_files(float.h HAVE_FLOAT_H)
    check_include_files(limits.h HAVE_LIMITS_H)
    check_include_files(locale.h HAVE_LOCALE_H)
    check_include_files(math.h HAVE_MATH_H)
    check_include_files(setjmp.h HAVE_SETJMP_H)
    check_include_files(signal.h HAVE_SIGNAL_H)
    check_include_files(stdarg.h HAVE_STDARG_H)
    check_include_files(stddef.h HAVE_STDDEF_H)
    check_include_files(stdio.h HAVE_STDIO_H)
    check_include_files(stdlib.h HAVE_STDLIB_H)
    check_include_files(string.h HAVE_STRING_H)
    check_include_files(time.h HAVE_TIME_H)
    endif()
endmacro()
