// This file is autogenerated by CMake

 #ifndef __BUILD_NUMBER_H__
 #define __BUILD_NUMBER_H__

 #define BUILD_NUMBER "34"
 #define BUILD_HASH "ge9b2b12"
 #define VERSION_NUMBER "0.1.2"
 #define BUILD_INFO "v" VERSION_NUMBER "-" BUILD_NUMBER "-" BUILD_HASH ""
  
#endif // __BUILD_NUMBER_H__