/*--------------------------------------------------------------------------
 * This file is autogenerated from config.h.in 
 * during the cmake configuration of your project. If you need to make changes
 * edit the original file NOT THIS FILE.
 * --------------------------------------------------------------------------*/
#ifndef INCLUDE_CONFIG_H
#define INCLUDE_CONFIG_H

/* Define to 1 if you have the <stddef.h> */
#define HAVE_STDDEF_H 1

/* Define to 1 if you want to use Lua */
/* #undef USE_LUA */

/* Define to 1 if you have a compatible Lua 5.3 install */
/* #undef HAVE_LUA_53 */

/* Define to 1 if you want to disable cURL support */
/* #undef DISABLE_CURL */

/* Define to 1 if you want to disable auto update support */
/* #undef DISABLE_AUTO_UPDATE */

/* Define to 1 if you have <curl/curl.h> */
#define HAVE_CURL_H 1

/* Define to 1 if you have <string.h> */
#define HAVE_STRING_H 1

/* Define to 1 if you have <strings.h> */
#define HAVE_STRINGS_H 1

/* Define to 1 if you want to use threading */
#define HAVE_THREADS 1

/* Define to 1 if you have <pthread.h> */
#define HAVE_PTHREAD_H 1

#endif /* INCLUDE_CONFIG_H */
