name: ci

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # os: [ubuntu-latest, ubuntu-18.04, ubuntu-22.04, macos-latest, macos-10.15, macos-12, windows-latest, windows-2019]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Packages (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-18.04' || matrix.os == 'ubuntu-22.04' }}
        run: |
          sudo apt update
          sudo apt install flex

      - name: Install Packages (MacOS)
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'macos-10.15' || matrix.os == 'macos-12' }}
        run: |
          brew update
          brew install flex

      - name: Install Packages (Windows)
        if: ${{ matrix.os == 'windows-latest' || matrix.os == 'windows-2019' }} 
        run: choco install winflexbison

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
